@startuml
skinparam classAttributeIconSize 0
hide circle
left to right direction
skinparam linetype ortho
skinparam packageStyle rectangle

package "NguoiDung" {
  abstract class NguoiDung {
    +maTK: String
    +hoTen: String
    +email: String
    +soDienThoai: String
    +tenDangNhap: String
    +matKhau: String
    +isActive: boolean
    +vaiTro: VaiTro
  }

  class ThuThu {
    +maThuThu: String
  }

  class DocGia {
    +maDocGia: String
    +diaChi: String
    +ngayDangKy: Date
  }

  class QuanTriVien {
    +maQuanTri: String
  }

  NguoiDung <|-- ThuThu
  NguoiDung <|-- DocGia
  NguoiDung <|-- QuanTriVien
}

package "QuanLySach" {
  class DanhMucSach {
    +maDanhMuc: String
    +tenDanhMuc: String
    +moTa: String
    +viTriKe: String
    +dangSuDung: boolean
  }

  class DauSach {
    +maDauSach: String
    +tenSach: String
    +tacGia: String
    +chuDe: String
    +nhaXuatBan: String
    +namXuatBan: int
    +isbn: String
    +viTriKho: String
    +trangThai: String
  }

  class QuyenSach {
    +maQuyenSach: String
    +ngayNhap: Date
    +tinhTrang: String
    +trangThai: TrangThaiQuyenSach
    +viTri: String
  }

  DanhMucSach "1" o-- "0..*" DauSach : phan_loai
  DauSach "1" *-- "1..*" QuyenSach : bao_gom
}

package "MuonTra" {
  class PhieuDatMuon {
    +maPhieuDat: String
    +ngayDat: Date
    +trangThai: TrangThaiPhieuDat
  }

  class PhieuMuon {
    +maPhieuMuon: String
    +ngayMuon: Date
    +hanTra: Date
    +trangThai: TrangThaiPhieuMuon
    +tienPhat: double
    +daThuPhat: boolean
  }

  class PhieuMuonChiTiet {
    +soLuong: int
    +ngayTraThuc: Date
    +trangThai: TrangThaiChiTiet
  }

  PhieuDatMuon "1" --> "0..1" PhieuMuon : chuyen_thanh
  PhieuMuon "1" *-- "1..*" PhieuMuonChiTiet : gom_chi_tiet
}

package "HeThong" {
  class ThongBao {
    +maThongBao: String
    +noiDung: String
    +ngayGui: Date
    +trangThai: String
  }

  class NhatKyHeThong {
    +maNhatKy: String
    +hanhDong: String
    +thoiGian: Date
    +chiTiet: String
  }

  class CauHinhHeThong {
    +soNgayMuonToiDa: int
    +soSachMuonToiDa: int
    +phiPhatMoiNgay: double
  }
}

enum VaiTro {
  Admin
  ThuThu
  DocGia
}

enum TrangThaiQuyenSach {
  SanSang
  DangMuon
  MatHong
}

enum TrangThaiPhieuDat {
  ChoDuyet
  DaDuyet
  TuChoi
  DaChuyenPhieuMuon
}

enum TrangThaiPhieuMuon {
  DangMuon
  QuaHan
  DaTra
}

enum TrangThaiChiTiet {
  DangMuon
  DaTra
}

DocGia "1" -- "0..*" PhieuDatMuon : tao
DocGia "1" -- "0..*" PhieuMuon : muon
ThuThu "1" -- "0..*" PhieuDatMuon : duyet
ThuThu "1" -- "0..*" PhieuMuon : lap_xu_ly

PhieuMuonChiTiet "0..*" -- "1" QuyenSach : muon_quyen

DocGia "1" -- "0..*" ThongBao : nhan
QuanTriVien "1" -- "0..*" NhatKyHeThong : tao
QuanTriVien "1" -- "1" CauHinhHeThong : quan_ly

@enduml
